apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels:
    app: my-app
    type: front-end # or back-end

spec:
  containers: # it is a list
    - name: nginx-container
      image: nginx
      # inject secret in pod:
      # 1 ENV
      envFrom:
        - secretRef:
            name: app-secret
      # 2 Single ENV
      env:
        - name: bd_password
          valueFrom:
            configMapKeyRef:
              name: app-secret
              key: bd_password
      # 3 VOLUME
      volumes:
      - name: app-secret-volume
        configMap:
          name: app-secret