apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  db_host: bXlzcWw= # result of command: echo -n 'mysql' | base64
  bd_user: dXNlcg== # result of command: echo -n 'user' | base64
  bd_password: cGFzc3dvcmQ=  # result of command: echo -n 'password' | base64