apiVersion: v1 # needed to expose the ingress controller to external world
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 433
      protocol: TCP
      name: https
    selector:
      name: nginx-ingress
