apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        app: my-app
        type: front-end # or back-end
    spec:
      containers: # it is a list
        - name: nginx-container
          image: nginx
  replicas: 3