apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
    - name: web-app
      image: web-app
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "1Gi"
          cpu: 1