apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    - name: ngunx-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: NotIn
                values:
                  - Small